### ISSUE TITLE
Recommended repo tags

### ISSUE THREAD

**Issue by NewAlexandria** [Paraphraser/PiBuilder#1]
Hi, recommend adding some or all of these tags to make your repo more findable!

* IoT
* DIY
* docker-compose
* home-automation
* raspberry-pi
* raspberry-pi3
* starter-kit
* starter-app
* starters
* starter
* starter-project

hope helps.  Thanks for the work in this repo

**Comment by Paraphraser** [comment]
Thanks for your suggestion. Not being overly-familiar with GitHub it took me a while to figure out the how-to but I think I've implemented most of that (didn't really see the point in having so many "starter-" prefix instances).
