### ISSUE TITLE
[Question] NTP Configuration as part of PiBuilder

### ISSUE THREAD

**Issue by Noschvie** [Paraphraser/PiBuilder#3]
Regarding to your gist [RPi_local_NTP_servers.md](https://gist.github.com/Paraphraser/e1129880015203c29f5e1376c6ca4a08)

Can this be added as part of the settings of PiBuilder ?

Or how to configure the Pi / PiBuilder in case of running behind a pfsense with NTP service ?
Thanks!

**Comment by Paraphraser** [comment]
Setting local time-servers is part of PiBuilder. See [NTP tutorial](https://github.com/Paraphraser/PiBuilder/blob/master/tutorials/ntp.md). You will see that the first part of the tutorial is the same as the gist but the last part tells you how to set the patch file into PiBuilder and have it just work.

I can't answer the pfsense part of your question. Sorry.

**Comment by Noschvie** [comment]
Thanks for the link!
